### ISSUE TITLE
radon.metadata doesn't exist & load_balancing_policy key error

### ISSUE THREAD

**Issue by alahiff** [radon-provenance/radon-lib#1]
Hi @JeromeFuselier , I was asked to have a look at radon and do some tests. When I try to create the radon-web server Docker image following the instructions, I get this error:
```
...
  File "/code/radon-web/archive/forms.py", line 20, in <module>
    from radon.metadata import get_collection_validator, get_resource_validator
ModuleNotFoundError: No module named 'radon.metadata'
The command '/bin/sh -c python manage.py migrate --run-syncdb' returned a non-zero code: 1
```
Looking at the radon source code in GitHub `radon.metadata` doesn't seem to exist at all.

Also, running `radmin create` gives this error:
```
  File "/usr/local/lib/python3.6/site-packages/dse/cqlengine/connection.py", line 79, in __init__
    del self.cluster_options['load_balancing_policy']
KeyError: 'load_balancing_policy'
```
If I comment out this line in the Dockerfile:
```
RUN patch /usr/local/lib/python3.6/site-packages/dse/cqlengine/connection.py < patch/patch_dse.patch
```
then it works but there is a warning:
```
WARNING:dse.cluster:Cluster.__init__ called with contact_points specified, but load-balancing policies are not specified in some ExecutionProfiles. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['172.17.0.3'], EPs without explicit LBPs = ('EXEC_PROFILE_DEFAULT',))
```
There is a similar error when building the web server image:
```
KeyError: 'load_balancing_policy'
The command '/bin/sh -c python manage.py collectstatic --noinput' returned a non-zero code: 1
```

**Comment by JeromeFuselier** [comment]
Hi @alahiff,
The master branch for radon-web wasn't up to date when you tested it so it may work now that I pushed the latest release (1.0.1). This should fix the first error.

What version are using for dse-driver ? It should be 2.11.0 based on the requirements.txt in radon-lib. I don't have the error on my machine, I will try to install it on a fresh image to see if this comes from the latest release.

**Comment by alahiff** [comment]
Ok, I'll try the latest release rather than the master branch and see if that fixes the first error.

The dse-driver version is 2.11.0.

**Comment by alahiff** [comment]
I can confirm that using the latest release fixed the first problem.
